version: '3'

services:
  drone-server:
    image: drone/drone:0.8
    restart: always

    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - /etc/drone:/var/lib/drone
    env_file:
      - /etc/drone/server.env

  drone-agent:
    image: drone/drone:0.8
    restart: always
    command: agent

    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - /etc/drone/agent.env
